// Generated by LiveScript 1.2.0
(function(){
  var expect, index, MatchesProcessor;
  require('../../test_setup');
  expect = require('chai').expect;
  index = require('../../../');
  MatchesProcessor = index.processor.MatchesProcessor;
}).call(this);
