// Generated by LiveScript 1.2.0
(function(){
  var expect, index, RuleContainerParser;
  require('../../test_setup');
  expect = require('chai').expect;
  index = require('../../../');
  RuleContainerParser = index.processor.RuleContainerParser;
}).call(this);
